#!/bin/bash
# PVM One Management tool
scriptname="po_tool"
scriptversion="0.1.0"

cat="/bin/cat"
cut="/bin/cut"
sed="/bin/sed"
grep="/bin/grep"
service="/sbin/service"
pkill="/usr/bin/pkill"
if [[ -f /etc/pvm.conf ]]; then
. /etc/pvm.conf
fi

po_status()
{
	$service cman status
	$service rgmanager status
	$service ricci status
}

# this function stop sync/cluster operations on this node ...
po_stoppvm()
{
	local vml 	# List of running virtual machines on this node
	echo_info "All of the running virtual machines would be stopped ..."
	are_you_sure
	if [[ $? -eq 0 ]]; then exit 0; fi
	echo_info "Stop running virtual machines running on this server ..."
	vml=$( $pvmctl "status" | $sed -e "1d" )
	for i in $vml; do
		echo "Stopping $i ..."
		$pcad stop $i
	done
	/pvm/Scripts/pvmctl unloadvsws
	echo "Stopping cluster operation ..."
	$service rgmanager stop >/dev/null 2>&1
	$service ricci stop >/dev/null 2>&1
	$service cman stop >/dev/null 2>&1

	$pkill pcmd >/dev/null 2>&1
	$pkill -9 pcmd >/dev/null 2>&1
	$pkill sballd >/dev/null 2>&1
	$pkill -9 sballd >/dev/null 2>&1
}

po_startpvm()
{
	echo "Starting cluster ..."
	$service cman start >/dev/null 2>&1
	if [[ $? -ne "0" ]]; then
		echo "Error: Can't start cluster engine ..."
		exit 1
	fi
	$service ricci start >/dev/null 2>&1
	$service rgmanager start >/dev/null 2>&1
	if [[ $? -ne "0" ]]; then
		echo "Error: Can't start resourse manager ..."
		exit 1
	fi
	/pvm/Scripts/pvmctl loadvsws 
	if [[ -f /home/pvm/pcm/pcmd ]]; then
		/home/pvm/pcm/pcmd
	else 
		if [[ -f /home/pvm/pcm/sballd ]]; then
			/home/pvm/sball/sballd
		fi
	fi
	if [[ -f /etc/pvm/pvm_po_pc ]]; then
		. /etc/pvm/pvm_po_pc
	fi
}

po_help()
{
	$cat <<-end-of-help
$scriptname $scriptversion
$scriptname is PVM one managent tool.

        usage:  status			- show pvm status.
                stoppvm			- stop pvm operation, preparing node to shutdown
                startpvm		- start pvm operation
	end-of-help
}


case "$1" in
	"status")
		po_status
		;;
	"stoppvm")
		po_stoppvm
		;;
	"startpvm")
		po_startpvm
		;;
	"help")
		po_help
		;;
	*)
		echo "Failed: bad command, use \"$scriptname help\" for more detail."
		;;
esac

