#!/bin/sh
#
# Hourse of VM Service file...
# USAGE: pvm-vm-service-hourse host {start,restart,stop,status}

# history
# 1388-12-18 by hamid jafarian
#	* use "/dev/null" if $log_file doen't exist

. /etc/pvm.conf

log_file=$( gen_log_file_fpath "$cf_vm_services_log_file" )

echo "* `date` host: `uname -n` | action: $2 | vm: $1"  >>"$log_file"
$pvm_vm_service ${1} ${2} >>"$log_file" 2>&1

